{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-macosx64/2.3.0-SNAPSHOT/okio-macosx64-2.3.0-SNAPSHOT.module",
    "group": "com.squareup.okio",
    "module": "okio-macosx64",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio-metadata-2.3.0-SNAPSHOT.jar",
          "url": "okio-metadata-2.3.0-SNAPSHOT.jar",
          "size": 13452,
          "sha1": "e08833f1b2cdfa6479f296f09c57f5f144cbd887",
          "md5": "224e0011543fc3462b4bc62749d8ed52"
        }
      ]
    }
  ]
}
