{
  "formatVersion": "1.0",
  "component": {
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "iosArm64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-iosarm64/2.3.0-SNAPSHOT/okio-iosarm64-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-iosarm64",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "iosX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-iosx64/2.3.0-SNAPSHOT/okio-iosx64-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-iosx64",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-js/2.3.0-SNAPSHOT/okio-js-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-js",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../okio-js/2.3.0-SNAPSHOT/okio-js-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-js",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio/2.3.0-SNAPSHOT/okio-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../okio/2.3.0-SNAPSHOT/okio-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "linuxX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-linuxx64/2.3.0-SNAPSHOT/okio-linuxx64-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-linuxx64",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "macosX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-macosx64/2.3.0-SNAPSHOT/okio-macosx64-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-macosx64",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.3.0-SNAPSHOT/okio-metadata-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.3.0-SNAPSHOT"
      }
    },
    {
      "name": "winX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../okio-winx64/2.3.0-SNAPSHOT/okio-winx64-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-winx64",
        "version": "2.3.0-SNAPSHOT"
      }
    }
  ]
}
