{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.3.0-SNAPSHOT/okio-multiplatform-2.3.0-SNAPSHOT.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "iosX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio.klib",
          "url": "okio-iosx64-2.3.0-SNAPSHOT.klib",
          "size": 199935,
          "sha1": "96d96645dc0bb88dabeee31f376edb00e13d336b",
          "md5": "6cc35a218881669677aeb6d2a11dd274"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.3.0-SNAPSHOT/okio-metadata-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.3.0-SNAPSHOT"
      }
    }
  ]
}
