{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.3.0-SNAPSHOT/okio-multiplatform-2.3.0-SNAPSHOT.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio-js-2.3.0-SNAPSHOT.jar",
          "url": "okio-js-2.3.0-SNAPSHOT.jar",
          "size": 127077,
          "sha1": "6a27e97b397d946cb5839d03e0d45a1d21c903b7",
          "md5": "4aa99601876581bbef85eeb59bee1462"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio-js-2.3.0-SNAPSHOT.jar",
          "url": "okio-js-2.3.0-SNAPSHOT.jar",
          "size": 127077,
          "sha1": "6a27e97b397d946cb5839d03e0d45a1d21c903b7",
          "md5": "4aa99601876581bbef85eeb59bee1462"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.3.0-SNAPSHOT/okio-metadata-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.3.0-SNAPSHOT"
      }
    }
  ]
}
