{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.3.0-SNAPSHOT/okio-multiplatform-2.3.0-SNAPSHOT.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "linuxX64-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio.klib",
          "url": "okio-linuxx64-2.3.0-SNAPSHOT.klib",
          "size": 199952,
          "sha1": "df553bf25ea4a916a399ff677b1429bd52c43cec",
          "md5": "208fb3473b2afc9424a26d011bd2fdb6"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.3.0-SNAPSHOT/okio-metadata-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.3.0-SNAPSHOT"
      }
    }
  ]
}
