{
  "formatVersion": "1.0",
  "component": {
    "url": "../../okio-multiplatform/2.3.0-SNAPSHOT/okio-multiplatform-2.3.0-SNAPSHOT.module",
    "group": "com.squareup.okio",
    "module": "okio-multiplatform",
    "version": "2.3.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "5.4.1",
      "buildId": "szn36d2v5raydoz2vy32fifiuy"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.usage": "java-api-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.3.0-SNAPSHOT.jar",
          "url": "okio-2.3.0-SNAPSHOT.jar",
          "size": 220643,
          "sha1": "d56fbb2b605ed99b79a01c6761fe3e0076959fff",
          "md5": "5a2a91ac1da3d56381353a7852a53c82"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime-jars",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.50-eap-5"
          }
        }
      ],
      "files": [
        {
          "name": "okio-jvm-2.3.0-SNAPSHOT.jar",
          "url": "okio-2.3.0-SNAPSHOT.jar",
          "size": 220643,
          "sha1": "d56fbb2b605ed99b79a01c6761fe3e0076959fff",
          "md5": "5a2a91ac1da3d56381353a7852a53c82"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../okio-metadata/2.3.0-SNAPSHOT/okio-metadata-2.3.0-SNAPSHOT.module",
        "group": "com.squareup.okio",
        "module": "okio-metadata",
        "version": "2.3.0-SNAPSHOT"
      }
    }
  ]
}
